-- vim.api.nvim_create_autocmd("FileType",
--     {
--         pattern = "json",
--         callback = function()
--             vim.lsp.start({
--                 name = "ngen-lsp",
--                 cmd = { "/Users/austinraney/github/ngen-lsp/go/ngen-lsp" },
--                 root_dir = vim.fs.dirname(vim.fs.find({ "test.json" }, { upward = true })[1])
--             })
--         end
--     }
-- )


-- WIP
-- vim.api.nvim_create_autocmd("FileType",
--     {
--         pattern = "json",
--         callback = function()
--             vim.lsp.start({
--                 name = "ngen-lsp",
--                 cmd = { "/Users/austinraney/github/ngen-lsp/venv/bin/python", "/Users/austinraney/github/ngen-lsp/main.py" },
--                 root_dir = vim.fs.dirname(vim.fs.find({ "test.json" }, { upward = true })[1])
--             })
--         end
--     }
-- )
