#!/bin/sh

#####################################
# Print bib reference for input doi #
#####################################

ID="$1"
URL="https://doi2bib.org/2/doi2bib?id="

curl -X GET "${URL}${ID}"

