#!/bin/bash

# Palm rest = Ts0P
# Max battery = TB0T
TEMP=$(istats scan Ts0P | awk '{print $5}')
pid=$(pgrep \"Macs Fan Control.app\")

# Open Macs Fan Control if not already running
# and battery temp greater than 36.9 degree C.
if [[ (-z $FAN_CONTROL) && ($TEMP > 36.9) ]]; then
	open "/Applications/Macs Fan Control.app";
	osascript -e 'tell application "Macs Fan Control" to close window 1';
	export FAN_CONTROL=true
elif [[ -n $FAN_CONTROL ]]; then
	# Kill PID of Macs Fan Control App
	kill $(pgrep \"Macs Fan Control.app\");
	# Set FAN_CONTROL environment variable
	# to empty string
	export FAN_CONTROL=
else
	:	
fi
