#!/bin/bash

# Get shit done
# This will block the connection to $SITES for a user specified time

SITES="www.facebook.com www.instagram.com www.twitter.com www.espn.com www.youtube.com www.reddit.com"
HOSTFILE="/etc/hosts"

print_help(){
	echo -e "    gsd -- A tool for getting stuff done\n"
	echo "        gsd [time-in-minutes]"
	echo "        h|-h show this help page"
	echo "        p|--play turn off gsd"
}

remove_old_proc(){
	PREVPID=$(ps -f -a | grep "[g]sd" | sed -E "s/ +/ /g" | cut -d ' ' -f3);
	for pid in $PREVPID;
	do
		kill $(pgrep -P "$pid") "$pid"
	done
}

add_sleep_and_remove(){
	for SITE in $SITES
	do
		echo -e "127.0.0.1\t${SITE}\t#gsd" >> $HOSTFILE
	done
	dscacheutil -flushcache
	sleep $(expr "$1" \* 60)
	sed -i -e '/#gsd$/d' $HOSTFILE
	dscacheutil -flushcache
}

case "$1" in
	"h"|"-h"|"")
	print_help
		;;
	"p"|"--play")
	remove_old_proc
	sed -i -e '/#gsd$/d' $HOSTFILE
	dscacheutil -flushcache
	exit 0
	;;
	*)
	remove_old_proc
	add_sleep_and_remove "$1" &
	;;
esac

# ps -o etime= -p "$$" 

# if [[ "$1" == "--play" ]]; then
# 	sed -i -e '/#gsd$/d' $HOSTFILE
# 	dscacheutil -flushcache
# 	exit 0
# elif [[ "$1" == ""]]
# 	sed -i -e '/#gsd$/d' $HOSTFILE
# 	for SITE in $SITES
# 	do
# 		echo -e "127.0.0.1\t${SITE}\t#gsd" >> $HOSTFILE
# 	done
# 	echo "work mode enabled, run with --play to disable"
# 	sleep_and_remove "$1" &
# 	# st=$(expr "$1" \* 60)
# 	# sleep "$st"
# 	# sed -i -e '/#gsd$/d' $HOSTFILE
# fi
