#!/usr/bin/env zsh

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
# yabai -m config layout                       bsp
yabai -m config top_padding                  12
yabai -m config bottom_padding               12
yabai -m config left_padding                 12
yabai -m config right_padding                12
yabai -m config window_gap                   06


# Helper functions
function thirds(){
if [ 3 -eq `yabai -m query --windows --display | jq '.[] | select(.hidden == 0)' | jq -s 'length'` ];
then
	yabai -m config layout float;

	get_window_ids(){
	yabai -m query --windows --display | jq '.[] | select(.hidden == 0) | .id'
	}

	ids=( $(get_window_ids) );
	for i in $(seq 1 3);
	do
		yabai -m window ${ids[$i]} --grid 1:3:$(expr ${i} - 1):0:1:1;
	done
else
yabai -m config layout bsp;
fi
}

# signals
## <rows>:<cols>:<start-x>:<start-y>:<width>:<height>
yabai -m signal --add event=window_created \
action="${functions[thirds]}"

yabai -m signal --add event=window_destroyed \
action="${functions[thirds]}"

yabai -m signal --add event=window_minimized \
action="${functions[thirds]}"

yabai -m signal --add event=window_deminimized \
action="${functions[thirds]}"

yabai -m signal --add event=application_visible \
action="${functions[thirds]}"

yabai -m signal --add event=application_hidden \
action="${functions[thirds]}"

yabai -m signal --add event=application_activated \
action="${functions[thirds]}"

yabai -m signal --add event=application_deactivated \
action="${functions[thirds]}"

